name: firebase_functions_interop
description: Firebase Cloud Functions SDK for Dart written as a JS interop wrapper for official Node.js SDK.
version: 2.0.0
homepage: https://www.github.com/pulyaevskiy/firebase-functions-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.7
  meta: ^1.11.0
  node_interop: ^2.1.0
  node_io: ^2.3.0
  node_http:
    git:
      url: https://github.com/JuntoChat/node-interop.git
      path: node_http
  firebase_admin_interop:
    git:
      url: https://github.com/dannnnthemannnn/firebase-admin-interop.git


dev_dependencies:
  test: ^1.24.3
